Refactor AccumSumFloat/AccumNanSumFloat temp work
rtosholdings/riptide_cpp pull request #69
Opened 2021-11-30 21:10 UTC by OrestZborowski-SIG

Add support for GroupBy methods to accept shared temp buffer and final pass indication.
Allocate shared temp buffer for multithreaded and non-multithreaded cases.
Have AccumSumFloat/AccumNanSumFloat use shared temp buffer and final pass downsample.
Restores performance to original (unsafe) version.
Fixes rtosholdings/riptable#258

2021-11-30 21:13 UTC, OrestZborowski-SIG commented
This is a rather simplistic refactoring (hoisting?) of allocations up to the top level, so the work can be performed incrementally on the same shared buffers. I also added the ability to perform the down-sampling only at the end of the final pass.

2021-12-01 13:27 UTC, jack-pappas requested changes

2021-12-01 13:27 UTC, jack-pappas commented on src/GroupBy.cpp
> +                    pTmpArray = WORKSPACE_ALLOC(tempItemSize * (binHigh - binLow));
Please add a check here for ``pTmpArray`` being nullptr, in case a process gets near it's memory limit and ``WORKSPACE_ALLOC`` returns nullptr. Otherwise, the compute function may attempt to deref the pointer to temp. storage and cause a segfault. However, the check will be slightly more complex than those above, because if the allocation fails you'll need to free any other storage (temporary or otherwise) in earlier iterations of the loop before returning.

2021-12-01 13:29 UTC, jack-pappas commented on src/GroupBy.cpp
> +                    pTmpArray = WORKSPACE_ALLOC(tempItemSize * (binHigh - binLow));
Also, shouldn't the number of elements in the allocated temp-storage array be ``unique_rows`` like the other arrays allocated just above here?

2021-12-01 13:33 UTC, OrestZborowski-SIG commented on src/GroupBy.cpp
> +                    pTmpArray = WORKSPACE_ALLOC(tempItemSize * (binHigh - binLow));
No. The temporary buffer is spanned by the bins and not the data rows.

2021-12-01 15:21 UTC, OrestZborowski-SIG commented on src/CommonInc.h
> +namespace internal
@staffantj this is my simple RAII wrapper for FmAlloc'ed memory. It does the job for now, handling cleanup in this change, but we may want to improve/extend it (and obviously use it elsewhere)

2021-12-01 15:42 UTC, staffantj reviewed
fn_mem_deleter works for me.

2021-12-01 22:14 UTC, jack-pappas approved these changes

2021-12-02 12:43 UTC, merged